import type {
  Achievement,
  ArabicVariant,
  Course,
  DialectComparison,
  Expression,
  VariantSlug,
  Vocab,
} from "./types";

export const VARIANTS: ArabicVariant[] = [
  {
    slug: "fusha",
    name: "Arabe standard (Fusha)",
    nativeName: "الفصحى",
    region: "Monde arabe",
    description: "La forme moderne écrite et médiatique, comprise partout.",
    speakers: "~400 M compris",
    available: true,
  },
  {
    slug: "libanais",
    name: "Libanais",
    nativeName: "لبناني",
    region: "Levant",
    description: "Mélodique, urbain, très parlé dans la diaspora.",
    speakers: "~15 M",
    available: true,
  },
  {
    slug: "darija",
    name: "Darija marocaine",
    nativeName: "الدارجة",
    region: "Maroc",
    description: "Riche en berbère, français et espagnol.",
    speakers: "~35 M",
    available: true,
  },
  {
    slug: "egyptien",
    name: "Égyptien",
    nativeName: "مصري",
    region: "Égypte",
    description: "Le dialecte du cinéma arabe, largement compris.",
    speakers: "~100 M",
    available: true,
  },
  {
    slug: "algerien",
    name: "Algérien",
    nativeName: "دزيري",
    region: "Algérie",
    description: "Proche de la darija, teinté d'histoire.",
    speakers: "~40 M",
    available: true,
  },
  {
    slug: "tunisien",
    name: "Tunisien",
    nativeName: "تونسي",
    region: "Tunisie",
    description: "Doux, méditerranéen.",
    speakers: "~12 M",
    available: true,
  },
  {
    slug: "golfe",
    name: "Arabe du Golfe",
    nativeName: "خليجي",
    region: "Péninsule Arabique",
    description: "Parlé aux Émirats, en Arabie, au Koweït.",
    speakers: "~40 M",
    available: true,
  },
  {
    slug: "classique",
    name: "Arabe classique",
    nativeName: "الفصحى التراثية",
    region: "Textes anciens",
    description: "Pour lire poésie, littérature et textes classiques.",
    speakers: "Lecture",
    available: true,
  },
];

export const VARIANT_LABEL: Record<string, string> = Object.fromEntries(
  VARIANTS.map((v) => [v.slug, v.name]),
);

// BCP-47 locale used for speech synthesis (Web Speech API). The browser
// falls back to its closest available Arabic voice when an exact locale
// isn't installed, so this is best-effort rather than a strict guarantee.
export const VARIANT_LANG: Record<VariantSlug, string> = {
  fusha: "ar-SA",
  libanais: "ar-LB",
  darija: "ar-MA",
  egyptien: "ar-EG",
  algerien: "ar-DZ",
  tunisien: "ar-TN",
  golfe: "ar-AE",
  classique: "ar-SA",
};

export const OBJECTIVES = [
  "Parler avec ma famille",
  "Voyager",
  "Vivre dans un pays arabe",
  "Comprendre la culture",
  "Travailler",
  "Lire et écrire",
  "Comprendre les médias",
  "Comprendre l'arabe classique",
  "Autre",
];

export const INTERESTS = [
  "Famille",
  "Voyage",
  "Cuisine",
  "Musique",
  "Culture",
  "Religion & histoire",
  "Travail",
  "Relations sociales",
  "Cinéma & séries",
  "Actualité",
  "Vie quotidienne",
  "Entrepreneuriat",
];

export const EXPRESSIONS: Expression[] = [
  {
    id: "e1",
    variant: "libanais",
    arabic: "كيفك؟",
    translit: "kifak? / kifik?",
    translation: "Comment vas-tu ?",
    note: "Informel, à Beyrouth. Réponse standard : Mnih (bien).",
  },
  {
    id: "e2",
    variant: "fusha",
    arabic: "كَيْفَ حَالُكَ؟",
    translit: "kayfa ḥāluka?",
    translation: "Comment vas-tu ? (standard)",
    note: "Forme classique, valable partout à l'écrit.",
  },
  {
    id: "e3",
    variant: "darija",
    arabic: "كيداير؟",
    translit: "kidayr? / kidayra?",
    translation: "Comment ça va ?",
    note: "Au Maroc, informel. Réponse : labas (ça va).",
  },
  {
    id: "e4",
    variant: "egyptien",
    arabic: "إزيك؟",
    translit: "izzayak? / izzayik?",
    translation: "Comment vas-tu ?",
    note: "Le plus reconnaissable du monde arabe grâce au cinéma égyptien.",
  },
  {
    id: "e5",
    variant: "algerien",
    arabic: "لاباس؟",
    translit: "labes?",
    translation: "Ça va ?",
    note: "Salutation courante, très proche de la darija marocaine.",
  },
  {
    id: "e6",
    variant: "tunisien",
    arabic: "شنية الحوال؟",
    translit: "chnia el ahwel?",
    translation: "Comment ça va ?",
    note: "Doux et méditerranéen, teinté d'italien et de français.",
  },
  {
    id: "e7",
    variant: "golfe",
    arabic: "شلونك؟",
    translit: "shlonak? / shlonik?",
    translation: "Comment vas-tu ?",
    note: "Utilisé aux Émirats, en Arabie Saoudite et au Koweït.",
  },
  {
    id: "e8",
    variant: "classique",
    arabic: "كَيْفَ حَالُكَ يَا صَدِيقِي؟",
    translit: "kayfa ḥāluka yā ṣadīqī?",
    translation: "Comment vas-tu, mon ami ?",
    note: "Registre littéraire, utilisé en poésie et dans les textes anciens.",
  },
];

export const VOCAB: Vocab[] = [
  { id: "v1", variant: "fusha", arabic: "مَرْحَبًا", translit: "marḥaban", translation: "Bonjour", category: "Salutations" },
  { id: "v2", variant: "fusha", arabic: "شُكْرًا", translit: "shukran", translation: "Merci", category: "Salutations" },
  { id: "v3", variant: "fusha", arabic: "نَعَم", translit: "naʿam", translation: "Oui", category: "Base" },
  { id: "v4", variant: "fusha", arabic: "لا", translit: "lā", translation: "Non", category: "Base" },
  { id: "v5", variant: "fusha", arabic: "مِنْ فَضْلِك", translit: "min faḍlik", translation: "S'il te plaît", category: "Salutations" },
  { id: "v6", variant: "libanais", arabic: "أهلاً", translit: "ahla", translation: "Salut", category: "Salutations" },
  { id: "v7", variant: "libanais", arabic: "منيح", translit: "mnih", translation: "Bien", category: "Base" },
  { id: "v8", variant: "libanais", arabic: "شو", translit: "shu", translation: "Quoi", category: "Questions" },
  { id: "v9", variant: "libanais", arabic: "بحبك", translit: "bḥibbak", translation: "Je t'aime", category: "Émotions" },
  { id: "v10", variant: "libanais", arabic: "يلا", translit: "yalla", translation: "Allez / Vas-y", category: "Base" },
  { id: "v11", variant: "darija", arabic: "لاباس", translit: "labas", translation: "Ça va", category: "Salutations" },
  { id: "v12", variant: "darija", arabic: "بزّاف", translit: "bezzaf", translation: "Beaucoup", category: "Base" },
  { id: "v13", variant: "darija", arabic: "واخا", translit: "wakha", translation: "D'accord", category: "Base" },
  { id: "v14", variant: "darija", arabic: "فين", translit: "fin", translation: "Où", category: "Questions" },
  { id: "v15", variant: "darija", arabic: "بسلامة", translit: "bslama", translation: "Au revoir", category: "Salutations" },
  { id: "v16", variant: "egyptien", arabic: "إزيك", translit: "izzayak", translation: "Comment vas-tu", category: "Salutations" },
  { id: "v17", variant: "egyptien", arabic: "كويس", translit: "kwayyes", translation: "Bien", category: "Base" },
  { id: "v18", variant: "egyptien", arabic: "إيه", translit: "eh", translation: "Quoi", category: "Questions" },
  { id: "v19", variant: "egyptien", arabic: "خالص", translit: "khales", translation: "Complètement", category: "Base" },
  { id: "v20", variant: "egyptien", arabic: "معلش", translit: "ma'lesh", translation: "Pas grave / désolé", category: "Base" },
  { id: "v21", variant: "algerien", arabic: "لاباس", translit: "labes", translation: "Ça va", category: "Salutations" },
  { id: "v22", variant: "algerien", arabic: "بزاف", translit: "bezzef", translation: "Beaucoup", category: "Base" },
  { id: "v23", variant: "algerien", arabic: "واش", translit: "wesh", translation: "Quoi", category: "Questions" },
  { id: "v24", variant: "algerien", arabic: "صحيت", translit: "saha", translation: "Merci / bravo", category: "Salutations" },
  { id: "v25", variant: "algerien", arabic: "بصح", translit: "besseh", translation: "Mais / vraiment", category: "Base" },
  { id: "v26", variant: "tunisien", arabic: "أهلا", translit: "ahla", translation: "Salut", category: "Salutations" },
  { id: "v27", variant: "tunisien", arabic: "برشة", translit: "barsha", translation: "Beaucoup", category: "Base" },
  { id: "v28", variant: "tunisien", arabic: "شنوة", translit: "chnowa", translation: "Quoi", category: "Questions" },
  { id: "v29", variant: "tunisien", arabic: "يعيشك", translit: "yaïchek", translation: "Merci (litt. qu'il te fasse vivre)", category: "Salutations" },
  { id: "v30", variant: "tunisien", arabic: "باهي", translit: "beheh", translation: "D'accord / bien", category: "Base" },
  { id: "v31", variant: "golfe", arabic: "مرحبا", translit: "marhaba", translation: "Bienvenue", category: "Salutations" },
  { id: "v32", variant: "golfe", arabic: "زين", translit: "zein", translation: "Bien / bon", category: "Base" },
  { id: "v33", variant: "golfe", arabic: "شنو", translit: "shnu", translation: "Quoi", category: "Questions" },
  { id: "v34", variant: "golfe", arabic: "يعطيك العافية", translit: "ya'tik al-'afya", translation: "Merci pour ton effort", category: "Salutations" },
  { id: "v35", variant: "golfe", arabic: "وايد", translit: "wayed", translation: "Beaucoup", category: "Base" },
  { id: "v36", variant: "classique", arabic: "مَرْحَبًا", translit: "marḥaban", translation: "Bienvenue", category: "Salutations" },
  { id: "v37", variant: "classique", arabic: "جَزِيلُ الشُّكْر", translit: "jazīl ash-shukr", translation: "Mille mercis", category: "Salutations" },
  { id: "v38", variant: "classique", arabic: "كَثِيرًا", translit: "kathīran", translation: "Beaucoup", category: "Base" },
  { id: "v39", variant: "classique", arabic: "مَاذَا", translit: "mādhā", translation: "Quoi", category: "Questions" },
  { id: "v40", variant: "classique", arabic: "بِإِذْنِكَ", translit: "bi-idhnika", translation: "Avec ta permission", category: "Base" },
];

// ---- COURSES ----
function mkLesson(id: string, moduleId: string, title: string, desc: string, minutes = 8): Course["modules"][number]["lessons"][number] {
  return {
    id,
    moduleId,
    title,
    description: desc,
    minutes,
    xp: 15,
    steps: [
      { type: "intro", title, body: desc },
      { type: "flashcard", arabic: "مَرْحَبًا", translit: "marḥaban", translation: "Bonjour" },
      {
        type: "choice",
        prompt: "Que signifie ce mot ?",
        arabic: "شُكْرًا",
        translit: "shukran",
        options: ["Bonjour", "Merci", "S'il te plaît", "Au revoir"],
        correct: 1,
      },
      {
        type: "order",
        prompt: "Remets la phrase dans l'ordre : « Bonjour, comment vas-tu ? »",
        tokens: ["حالك", "كيف", "،", "مرحبا"],
        correct: ["مرحبا", "،", "كيف", "حالك"],
      },
      {
        type: "translate",
        prompt: "Traduis en français",
        arabic: "شُكْرًا",
        translit: "shukran",
        answer: "merci",
      },
      {
        type: "listen",
        arabic: "مَرْحَبًا",
        translit: "marḥaban",
        options: ["marḥaban", "shukran", "min faḍlik"],
        correct: 0,
      },
    ],
  };
}

export const COURSES: Course[] = [
  {
    id: "fusha-beginner",
    variant: "fusha",
    title: "Fusha — Débuter",
    description: "Les fondations : alphabet, sons et premiers échanges.",
    level: "A1",
    modules: [
      {
        id: "fusha-m1",
        courseId: "fusha-beginner",
        title: "Alphabet & prononciation",
        description: "Découvrir les lettres et sons de l'arabe.",
        xpReward: 120,
        lessons: [
          mkLesson("fusha-m1-l1", "fusha-m1", "Les 5 premières lettres", "ا ب ت ث ج"),
          mkLesson("fusha-m1-l2", "fusha-m1", "Voyelles courtes", "Fatḥa, kasra, ḍamma"),
          mkLesson("fusha-m1-l3", "fusha-m1", "Sons emphatiques", "ص ض ط ظ"),
        ],
      },
      {
        id: "fusha-m2",
        courseId: "fusha-beginner",
        title: "Salutations",
        description: "Dire bonjour et politesse essentielle.",
        xpReward: 100,
        lessons: [
          mkLesson("fusha-m2-l1", "fusha-m2", "Bonjour et bonsoir", "مرحبا، مساء الخير"),
          mkLesson("fusha-m2-l2", "fusha-m2", "Merci et s'il te plaît", "شكرا، من فضلك"),
          mkLesson("fusha-m2-l3", "fusha-m2", "Comment vas-tu ?", "كيف حالك؟"),
        ],
      },
      {
        id: "fusha-m3",
        courseId: "fusha-beginner",
        title: "Se présenter",
        description: "Dire son nom, son âge, d'où l'on vient.",
        xpReward: 130,
        lessons: [
          mkLesson("fusha-m3-l1", "fusha-m3", "Je m'appelle…", "اسمي…"),
          mkLesson("fusha-m3-l2", "fusha-m3", "Je viens de…", "أنا من…"),
          mkLesson("fusha-m3-l3", "fusha-m3", "Enchanté", "تشرّفت"),
        ],
      },
    ],
  },
  {
    id: "libanais-beginner",
    variant: "libanais",
    title: "Libanais — Débuter",
    description: "Parler comme à Beyrouth, dans la famille et entre amis.",
    level: "A1",
    modules: [
      {
        id: "leb-m1",
        courseId: "libanais-beginner",
        title: "Salutations quotidiennes",
        description: "Kifak, ahla, marhaba.",
        xpReward: 100,
        lessons: [
          mkLesson("leb-m1-l1", "leb-m1", "Ahla et marhaba", "أهلا / مرحبا"),
          mkLesson("leb-m1-l2", "leb-m1", "Kifak / kifik", "كيفك"),
          mkLesson("leb-m1-l3", "leb-m1", "Mnih, tayyeb", "منيح، طيب"),
        ],
      },
      {
        id: "leb-m2",
        courseId: "libanais-beginner",
        title: "Famille & amis",
        description: "Parler des tiens.",
        xpReward: 110,
        lessons: [
          mkLesson("leb-m2-l1", "leb-m2", "Ma famille", "عيلتي"),
          mkLesson("leb-m2-l2", "leb-m2", "Mes amis", "رفقاتي"),
          mkLesson("leb-m2-l3", "leb-m2", "Je t'aime", "بحبك"),
        ],
      },
      {
        id: "leb-m3",
        courseId: "libanais-beginner",
        title: "Commander à manger",
        description: "Au restaurant, au café.",
        xpReward: 120,
        lessons: [
          mkLesson("leb-m3-l1", "leb-m3", "Je voudrais…", "بدي…"),
          mkLesson("leb-m3-l2", "leb-m3", "Un café stp", "قهوة لو سمحت"),
          mkLesson("leb-m3-l3", "leb-m3", "L'addition", "الحساب"),
        ],
      },
    ],
  },
  {
    id: "darija-beginner",
    variant: "darija",
    title: "Darija — Débuter",
    description: "Parler avec les Marocains dès demain.",
    level: "A1",
    modules: [
      {
        id: "dar-m1",
        courseId: "darija-beginner",
        title: "Expressions essentielles",
        description: "Salam, labas, wakha.",
        xpReward: 100,
        lessons: [
          mkLesson("dar-m1-l1", "dar-m1", "Salam et labas", "سلام، لاباس"),
          mkLesson("dar-m1-l2", "dar-m1", "Wakha & bslama", "واخا، بسلامة"),
          mkLesson("dar-m1-l3", "dar-m1", "Choukran bezzaf", "شكرا بزاف"),
        ],
      },
      {
        id: "dar-m2",
        courseId: "darija-beginner",
        title: "Faire connaissance",
        description: "Nom, origine, métier.",
        xpReward: 110,
        lessons: [
          mkLesson("dar-m2-l1", "dar-m2", "Smiti…", "سميتي…"),
          mkLesson("dar-m2-l2", "dar-m2", "Ana men…", "أنا من…"),
          mkLesson("dar-m2-l3", "dar-m2", "Kandir…", "كندير…"),
        ],
      },
      {
        id: "dar-m3",
        courseId: "darija-beginner",
        title: "Se déplacer en ville",
        description: "Taxi, souk, direction.",
        xpReward: 120,
        lessons: [
          mkLesson("dar-m3-l1", "dar-m3", "Fin kayn…", "فين كاين…"),
          mkLesson("dar-m3-l2", "dar-m3", "Bghit nemshi l…", "بغيت نمشي ل…"),
          mkLesson("dar-m3-l3", "dar-m3", "Chhal?", "شحال؟"),
        ],
      },
    ],
  },
  {
    id: "egyptien-beginner",
    variant: "egyptien",
    title: "Égyptien — Débuter",
    description: "Le dialecte du cinéma, compris dans tout le monde arabe.",
    level: "A1",
    modules: [
      {
        id: "egy-m1",
        courseId: "egyptien-beginner",
        title: "Salutations essentielles",
        description: "Izzayak, ahlan, kwayyes.",
        xpReward: 100,
        lessons: [
          mkLesson("egy-m1-l1", "egy-m1", "Ahlan et izzayak", "أهلا، إزيك"),
          mkLesson("egy-m1-l2", "egy-m1", "Kwayyes, ma'lesh", "كويس، معلش"),
          mkLesson("egy-m1-l3", "egy-m1", "Shukran khales", "شكرا خالص"),
        ],
      },
      {
        id: "egy-m2",
        courseId: "egyptien-beginner",
        title: "Faire connaissance",
        description: "Nom, origine, métier.",
        xpReward: 110,
        lessons: [
          mkLesson("egy-m2-l1", "egy-m2", "Ismi…", "اسمي…"),
          mkLesson("egy-m2-l2", "egy-m2", "Ana men…", "أنا من…"),
          mkLesson("egy-m2-l3", "egy-m2", "Bta'mal eh?", "بتعمل إيه؟"),
        ],
      },
      {
        id: "egy-m3",
        courseId: "egyptien-beginner",
        title: "Se déplacer au Caire",
        description: "Taxi, quartier, direction.",
        xpReward: 120,
        lessons: [
          mkLesson("egy-m3-l1", "egy-m3", "Fein…", "فين…"),
          mkLesson("egy-m3-l2", "egy-m3", "Ayez arouh l…", "عايز أروح ل…"),
          mkLesson("egy-m3-l3", "egy-m3", "Bikam da?", "بكام ده؟"),
        ],
      },
    ],
  },
  {
    id: "algerien-beginner",
    variant: "algerien",
    title: "Algérien — Débuter",
    description: "Parler comme à Alger, entre darija et histoire.",
    level: "A1",
    modules: [
      {
        id: "alg-m1",
        courseId: "algerien-beginner",
        title: "Expressions essentielles",
        description: "Labes, saha, wesh.",
        xpReward: 100,
        lessons: [
          mkLesson("alg-m1-l1", "alg-m1", "Labes et saha", "لاباس، صحيت"),
          mkLesson("alg-m1-l2", "alg-m1", "Wesh rak", "واش راك"),
          mkLesson("alg-m1-l3", "alg-m1", "Bezzef merci", "بزاف شكرا"),
        ],
      },
      {
        id: "alg-m2",
        courseId: "algerien-beginner",
        title: "Faire connaissance",
        description: "Nom, origine, métier.",
        xpReward: 110,
        lessons: [
          mkLesson("alg-m2-l1", "alg-m2", "Smiti…", "سميتي…"),
          mkLesson("alg-m2-l2", "alg-m2", "Ana men…", "أنا من…"),
          mkLesson("alg-m2-l3", "alg-m2", "Ndir…", "ندير…"),
        ],
      },
      {
        id: "alg-m3",
        courseId: "algerien-beginner",
        title: "Au marché",
        description: "Négocier, compter, remercier.",
        xpReward: 120,
        lessons: [
          mkLesson("alg-m3-l1", "alg-m3", "Chhal hada?", "شحال هذا؟"),
          mkLesson("alg-m3-l2", "alg-m3", "Ghali bezzef", "غالي بزاف"),
          mkLesson("alg-m3-l3", "alg-m3", "Saha ftourek", "صحة فطورك"),
        ],
      },
    ],
  },
  {
    id: "tunisien-beginner",
    variant: "tunisien",
    title: "Tunisien — Débuter",
    description: "Doux et méditerranéen, entre l'arabe, le français et l'italien.",
    level: "A1",
    modules: [
      {
        id: "tun-m1",
        courseId: "tunisien-beginner",
        title: "Salutations quotidiennes",
        description: "Ahla, chnia el ahwel, yaïchek.",
        xpReward: 100,
        lessons: [
          mkLesson("tun-m1-l1", "tun-m1", "Ahla et chniya ahwelek", "أهلا، شنية أحوالك"),
          mkLesson("tun-m1-l2", "tun-m1", "Behi, barsha behi", "باهي، برشة باهي"),
          mkLesson("tun-m1-l3", "tun-m1", "Yaïchek", "يعيشك"),
        ],
      },
      {
        id: "tun-m2",
        courseId: "tunisien-beginner",
        title: "Faire connaissance",
        description: "Nom, origine, métier.",
        xpReward: 110,
        lessons: [
          mkLesson("tun-m2-l1", "tun-m2", "Smiti…", "سميتي…"),
          mkLesson("tun-m2-l2", "tun-m2", "Ena men…", "آنا من…"),
          mkLesson("tun-m2-l3", "tun-m2", "Ta'mel fi eh?", "تعمل في إيه؟"),
        ],
      },
      {
        id: "tun-m3",
        courseId: "tunisien-beginner",
        title: "Au café",
        description: "Commander, discuter, remercier.",
        xpReward: 120,
        lessons: [
          mkLesson("tun-m3-l1", "tun-m3", "Nheb qahwa", "نحب قهوة"),
          mkLesson("tun-m3-l2", "tun-m3", "Chnowa el hsab?", "شنوة الحساب؟"),
          mkLesson("tun-m3-l3", "tun-m3", "Barsha yaïchek", "برشة يعيشك"),
        ],
      },
    ],
  },
  {
    id: "golfe-beginner",
    variant: "golfe",
    title: "Arabe du Golfe — Débuter",
    description: "Parlé aux Émirats, en Arabie Saoudite et au Koweït.",
    level: "A1",
    modules: [
      {
        id: "gol-m1",
        courseId: "golfe-beginner",
        title: "Salutations essentielles",
        description: "Marhaba, shlonak, zein.",
        xpReward: 100,
        lessons: [
          mkLesson("gol-m1-l1", "gol-m1", "Marhaba et shlonak", "مرحبا، شلونك"),
          mkLesson("gol-m1-l2", "gol-m1", "Zein, al-hamdulillah", "زين، الحمد لله"),
          mkLesson("gol-m1-l3", "gol-m1", "Ya'tik al-'afya", "يعطيك العافية"),
        ],
      },
      {
        id: "gol-m2",
        courseId: "golfe-beginner",
        title: "Faire connaissance",
        description: "Nom, origine, métier.",
        xpReward: 110,
        lessons: [
          mkLesson("gol-m2-l1", "gol-m2", "Ismi…", "اسمي…"),
          mkLesson("gol-m2-l2", "gol-m2", "Ana min…", "أنا من…"),
          mkLesson("gol-m2-l3", "gol-m2", "Ashtaghil…", "أشتغل…"),
        ],
      },
      {
        id: "gol-m3",
        courseId: "golfe-beginner",
        title: "Au souk",
        description: "Acheter, négocier, remercier.",
        xpReward: 120,
        lessons: [
          mkLesson("gol-m3-l1", "gol-m3", "Bekam hatha?", "بكم هذا؟"),
          mkLesson("gol-m3-l2", "gol-m3", "Wayed ghali", "وايد غالي"),
          mkLesson("gol-m3-l3", "gol-m3", "Mashkoor", "مشكور"),
        ],
      },
    ],
  },
  {
    id: "classique-beginner",
    variant: "classique",
    title: "Arabe classique — Débuter",
    description: "Pour lire la poésie, la littérature et les textes anciens.",
    level: "A1",
    modules: [
      {
        id: "cla-m1",
        courseId: "classique-beginner",
        title: "Formules de politesse",
        description: "Marhaban, jazil ash-shukr.",
        xpReward: 100,
        lessons: [
          mkLesson("cla-m1-l1", "cla-m1", "Marhaban et ahlan wa sahlan", "مرحبًا، أهلًا وسهلًا"),
          mkLesson("cla-m1-l2", "cla-m1", "Jazil ash-shukr", "جزيل الشكر"),
          mkLesson("cla-m1-l3", "cla-m1", "Bi-idhnika", "بإذنك"),
        ],
      },
      {
        id: "cla-m2",
        courseId: "classique-beginner",
        title: "Se présenter en fusha littéraire",
        description: "Nom, origine, profession.",
        xpReward: 110,
        lessons: [
          mkLesson("cla-m2-l1", "cla-m2", "Ismi…", "اسمي…"),
          mkLesson("cla-m2-l2", "cla-m2", "Anā min…", "أنا مِن…"),
          mkLesson("cla-m2-l3", "cla-m2", "Ta sharraftu", "تَشَرَّفْتُ"),
        ],
      },
      {
        id: "cla-m3",
        courseId: "classique-beginner",
        title: "Lire un texte simple",
        description: "Comprendre un court extrait classique.",
        xpReward: 130,
        lessons: [
          mkLesson("cla-m3-l1", "cla-m3", "Le vocabulaire des textes", "المفردات"),
          mkLesson("cla-m3-l2", "cla-m3", "La structure de la phrase", "تركيب الجملة"),
          mkLesson("cla-m3-l3", "cla-m3", "Premier poème court", "قصيدة قصيرة"),
        ],
      },
    ],
  },
];

export const DIALECT_COMPARISONS: DialectComparison[] = [
  {
    french: "Comment vas-tu ?",
    entries: [
      { variant: "fusha", arabic: "كَيْفَ حَالُكَ؟", translit: "kayfa ḥāluka?" },
      { variant: "libanais", arabic: "كيفك؟", translit: "kifak?" },
      { variant: "darija", arabic: "كيداير؟", translit: "kidayr?" },
      { variant: "egyptien", arabic: "إزيك؟", translit: "izzayak?" },
      { variant: "algerien", arabic: "لاباس؟", translit: "labes?" },
      { variant: "tunisien", arabic: "شنية أحوالك؟", translit: "chnia ahwelek?" },
      { variant: "golfe", arabic: "شلونك؟", translit: "shlonak?" },
      { variant: "classique", arabic: "كَيْفَ حَالُكَ يَا صَدِيقِي؟", translit: "kayfa ḥāluka yā ṣadīqī?" },
    ],
  },
  {
    french: "Merci",
    entries: [
      { variant: "fusha", arabic: "شُكْرًا", translit: "shukran" },
      { variant: "libanais", arabic: "مرسي / شكراً", translit: "mersi / shukran" },
      { variant: "darija", arabic: "شكرا بزاف", translit: "shukran bezzaf" },
      { variant: "egyptien", arabic: "شكراً", translit: "shukran" },
      { variant: "algerien", arabic: "صحيت", translit: "saha" },
      { variant: "tunisien", arabic: "يعيشك", translit: "yaïchek" },
      { variant: "golfe", arabic: "مشكور", translit: "mashkoor" },
      { variant: "classique", arabic: "جَزِيلُ الشُّكْر", translit: "jazīl ash-shukr" },
    ],
  },
  {
    french: "Combien ça coûte ?",
    entries: [
      { variant: "fusha", arabic: "بِكَمْ هَذَا؟", translit: "bikam hādhā?" },
      { variant: "libanais", arabic: "قدّيش؟", translit: "addēsh?" },
      { variant: "darija", arabic: "بشحال؟", translit: "bshḥal?" },
      { variant: "egyptien", arabic: "بكام دة؟", translit: "bikām da?" },
      { variant: "algerien", arabic: "شحال هذا؟", translit: "chhal hada?" },
      { variant: "tunisien", arabic: "شنوة الحساب؟", translit: "chnowa el hsab?" },
      { variant: "golfe", arabic: "بكم هذا؟", translit: "bekam hatha?" },
      { variant: "classique", arabic: "بِكَمْ هَذَا الشَّيْء؟", translit: "bikam hādhā sh-shayʾ?" },
    ],
  },
  {
    french: "Je t'aime",
    entries: [
      { variant: "fusha", arabic: "أُحِبُّكَ", translit: "uḥibbuka" },
      { variant: "libanais", arabic: "بحبك", translit: "bḥibbak" },
      { variant: "darija", arabic: "كنبغيك", translit: "kanbghik" },
      { variant: "egyptien", arabic: "بحبك", translit: "baḥibbak" },
      { variant: "algerien", arabic: "نحبك", translit: "nhebbek" },
      { variant: "tunisien", arabic: "نحبك", translit: "nheb'ek" },
      { variant: "golfe", arabic: "أحبك", translit: "aḥebbek" },
      { variant: "classique", arabic: "إِنِّي أُحِبُّكَ", translit: "innī uḥibbuka" },
    ],
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  { slug: "first-word", title: "Premier mot", description: "Tu as appris ton premier mot.", icon: "✶", unlocked: true },
  { slug: "first-lesson", title: "Première leçon", description: "Une leçon terminée.", icon: "◆", unlocked: true },
  { slug: "reader", title: "Lecteur débutant", description: "Lire 10 mots en arabe.", icon: "❋", unlocked: true },
  { slug: "week", title: "Une semaine régulière", description: "7 jours d'affilée.", icon: "✦", unlocked: false },
  { slug: "greetings", title: "Maître des salutations", description: "Toutes les salutations maîtrisées.", icon: "❖", unlocked: false },
  { slug: "100words", title: "100 mots maîtrisés", description: "100 mots dans ta mémoire.", icon: "◉", unlocked: false },
  { slug: "explorer-lb", title: "Explorateur du Liban", description: "Module libanais terminé.", icon: "▲", unlocked: false },
  { slug: "explorer-ma", title: "Explorateur du Maroc", description: "Module marocain terminé.", icon: "△", unlocked: false },
  { slug: "5min-chat", title: "Conversation de 5 min", description: "Une vraie discussion.", icon: "◐", unlocked: false },
];

export const ALPHABET_LETTERS = [
  { letter: "ا", name: "alif", sound: "a / â" },
  { letter: "ب", name: "bāʾ", sound: "b" },
  { letter: "ت", name: "tāʾ", sound: "t" },
  { letter: "ث", name: "thāʾ", sound: "th (think)" },
  { letter: "ج", name: "jīm", sound: "j / dj" },
  { letter: "ح", name: "ḥāʾ", sound: "ḥ guttural" },
  { letter: "خ", name: "khāʾ", sound: "kh (jota)" },
  { letter: "د", name: "dāl", sound: "d" },
  { letter: "ذ", name: "dhāl", sound: "th (this)" },
  { letter: "ر", name: "rāʾ", sound: "r roulé" },
  { letter: "ز", name: "zāy", sound: "z" },
  { letter: "س", name: "sīn", sound: "s" },
  { letter: "ش", name: "shīn", sound: "ch" },
  { letter: "ص", name: "ṣād", sound: "s emphatique" },
  { letter: "ض", name: "ḍād", sound: "d emphatique" },
  { letter: "ط", name: "ṭāʾ", sound: "t emphatique" },
  { letter: "ظ", name: "ẓāʾ", sound: "z emphatique" },
  { letter: "ع", name: "ʿayn", sound: "ʿ guttural" },
  { letter: "غ", name: "ghayn", sound: "gh (r français)" },
  { letter: "ف", name: "fāʾ", sound: "f" },
  { letter: "ق", name: "qāf", sound: "q profond" },
  { letter: "ك", name: "kāf", sound: "k" },
  { letter: "ل", name: "lām", sound: "l" },
  { letter: "م", name: "mīm", sound: "m" },
  { letter: "ن", name: "nūn", sound: "n" },
  { letter: "ه", name: "hāʾ", sound: "h aspiré" },
  { letter: "و", name: "wāw", sound: "w / ou" },
  { letter: "ي", name: "yāʾ", sound: "y / i" },
];

export const SCENARIOS = [
  { id: "intro", title: "Se présenter", desc: "Nom, origine, ce que tu fais." },
  { id: "resto", title: "Commander au restaurant", desc: "Menu, boissons, addition." },
  { id: "family", title: "Parler avec la famille", desc: "Les tiens, leurs nouvelles." },
  { id: "taxi", title: "Prendre un taxi", desc: "Direction, prix, discussion." },
  { id: "shopping", title: "Acheter quelque chose", desc: "Négocier au souk." },
  { id: "directions", title: "Demander son chemin", desc: "Se repérer en ville." },
  { id: "friends", title: "Entre amis", desc: "Blagues, plans, ambiances." },
  { id: "interview", title: "Entretien pro", desc: "Expérience, motivation." },
  { id: "travel", title: "Voyage", desc: "Aéroport, hôtel, découvertes." },
  { id: "free", title: "Discussion libre", desc: "Comme avec un pote." },
];

export const WEEKLY_ACTIVITY = [
  { day: "Lun", minutes: 12 },
  { day: "Mar", minutes: 18 },
  { day: "Mer", minutes: 8 },
  { day: "Jeu", minutes: 22 },
  { day: "Ven", minutes: 15 },
  { day: "Sam", minutes: 0 },
  { day: "Dim", minutes: 10 },
];

export const SKILL_SCORES = [
  { skill: "Vocabulaire", value: 68 },
  { skill: "Compréhension", value: 55 },
  { skill: "Expression orale", value: 42 },
  { skill: "Lecture", value: 60 },
  { skill: "Écriture", value: 30 },
  { skill: "Grammaire", value: 48 },
];